In [1]:
import pandas as pd

In [2]:
# Load the CSV file into a DataFrame
csv_file = 'securities.csv'
df = pd.read_csv(csv_file)

In [4]:
df

,Type,Market/Platform,Issuer,ISIN,Name,Issued amount,CCY,Listing Date,Coupon,Last Price
0,BondB,Bourse de Luxembourg,DEUTSCHE BANK AG,XS0461590985,DeutscheBank 05/07/2029 EURO STOXX 50 Index,"840,000",EUR,28/06/2024,NaN,100 i %28/06/24 15:01:10
1,BondB,Bourse de Luxembourg,DEUTSCHE BANK AG,XS0461629783,DeutscheBank 3% 28/06/2028,"11,070,000",EUR,28/06/2024,3 %,100 i %28/06/24 15:01:10
2,BondB,Euro MTF,DEUTSCHE BANK AG,XS0461588815,DeutscheBank 28/06/2027 EURO STOXX 50 Price ...,"8,122,000",EUR,27/06/2024,NaN,96.68 i %28/06/24 15:06:42
3,BondB,Euro MTF,DEUTSCHE BANK AG,XS0460092587,"DeutscheBank 5,2% 27/06/2029","10,500,000",USD,27/06/2024,5.2 %,99.41 i %28/06/24 15:07:24
4,CertificateC,Euro MTF,DEUTSCHE BANK AG,XS0460092660,DeutscheBank 22/06/2029 S&P 500 Index,NaN,USD,27/06/2024,NaN,100.11 i USD28/06/24 14:56:16
...,...,...,...,...,...,...,...,...,...,...
1017,BondB,Bourse de Luxembourg,DEUTSCHE BANK AG,DE0002461860,"DeutscheBank 5,5% 24/07/2028","250,000,000",DEM,24/07/1998,5.5 %,121.724 i %19/09/14 10:53:31
1018,BondB,Bourse de Luxembourg,DEUTSCHE BANK AG,XS0076085603,DeutscheBank 100 27/05/2027,"4,000,000,000",ZAR,27/05/1997,NaN,76.031 i %28/06/24 15:19:53
1019,BondB,Bourse de Luxembourg,DEUTSCHE BANK AG,DE0001892057,DeutscheBank 100 20/01/2032,"4,000,000,000,000",ITL,20/01/1997,NaN,71.932 i %28/06/24 15:19:56
1020,BondB,Bourse de Luxembourg,DEUTSCHE BANK AG,DE0001345940,DeutscheBank 100 18/11/2026,"4,000,000,000",DKK,18/11/1996,NaN,90.14 i %28/06/24 15:35:22
1021,BondB,Bourse de Luxembourg,DEUTSCHE BANK AG,DE0001342244,DeutscheBank 100 15/10/2026,"5,000,000,000,000",ITL,15/10/1996,NaN,91.011 i %28/06/24 15:22:53

In [3]:
# Identify duplicate rows
duplicates = df.duplicated()

# Count the number of duplicate rows
num_duplicates = duplicates.sum()
print(f"Number of duplicate rows: {num_duplicates}")

# Display duplicate rows
if num_duplicates > 0:
    print("Duplicate rows:")
    print(df[duplicates])

Number of duplicate rows: 14
Duplicate rows:
              Type       Market/Platform            Issuer          ISIN  \
160          BondB              Euro MTF  DEUTSCHE BANK AG  XS0461538398
180   CertificateC              Euro MTF  DEUTSCHE BANK AG  XS0460084568
560   CertificateC              Euro MTF  DEUTSCHE BANK AG  XS0459853262
1011      WarrantW              Euro MTF  DEUTSCHE BANK AG  DE000DB1CFC2
1012      WarrantW              Euro MTF  DEUTSCHE BANK AG  DE000DB1CFF5
1013      WarrantW              Euro MTF  DEUTSCHE BANK AG  DE000DB1CFG3
1014         BondB  Bourse de Luxembourg  DEUTSCHE BANK AG  XS0242439668
1015         BondB  Bourse de Luxembourg  DEUTSCHE BANK AG  XS0210953039
1016      WarrantW  Bourse de Luxembourg  DEUTSCHE BANK AG  DE000DB0A3K9
1017         BondB  Bourse de Luxembourg  DEUTSCHE BANK AG  DE0002461860
1018         BondB  Bourse de Luxembourg  DEUTSCHE BANK AG  XS0076085603
1019         BondB  Bourse de Luxembourg  DEUTSCHE BANK AG  DE0001892057
1020         BondB  Bourse de Luxembourg  DEUTSCHE BANK AG  DE0001345940
1021         BondB  Bourse de Luxembourg  DEUTSCHE BANK AG  DE0001342244

                                                   Name      Issued amount  \
160            DeutscheBank  31/07/2030  Bkt of Indices         20,000,000
180           DeutscheBank  18/01/2028 MSCI World Index                NaN
560   DeutscheBank  26/06/2026 MSCI Emerging Markets...                NaN
1011         DeutscheBank  Deutsche Bank US Value Index                NaN
1012       DeutscheBank  Deutsche Bank Euro Value Index                NaN
1013      DeutscheBank  Deutsche Bank Euro Growth Index                NaN
1014                        DeutscheBank FRN 15/02/2046         23,800,000
1015                        DeutscheBank FRN 23/02/2035        200,000,000
1016  DeutscheBank  Deutsche Bank Liquid Commodity I...                NaN
1017                       DeutscheBank 5,5% 24/07/2028        250,000,000
1018                        DeutscheBank 100 27/05/2027      4,000,000,000
1019                        DeutscheBank 100 20/01/2032  4,000,000,000,000
1020                        DeutscheBank 100 18/11/2026      4,000,000,000
1021                        DeutscheBank 100 15/10/2026  5,000,000,000,000

      CCY Listing Date Coupon                      Last Price
160   EUR   31/01/2024    NaN      100.2 i %28/06/24 15:07:43
180   USD   18/01/2024    NaN      100 i USD18/01/24 13:00:22
560   USD   01/07/2021    NaN   91.755 i USD28/06/24 14:55:50
1011  USD   30/03/2006    NaN   877.42 i USD30/03/06 13:15:20
1012  EUR   30/03/2006    NaN  1317.76 i EUR30/03/06 13:15:21
1013  EUR   30/03/2006    NaN   947.99 i EUR30/03/06 13:15:20
1014  EUR   15/02/2006    NaN       94.7 i %01/09/16 14:55:01
1015  EUR   23/02/2005    NaN         75 i %31/07/12 14:56:48
1016  EUR   27/02/2004    NaN   116 null EUR05/09/05 15:01:13
1017  DEM   24/07/1998  5.5 %    121.724 i %19/09/14 10:53:31
1018  ZAR   27/05/1997    NaN     76.031 i %28/06/24 15:19:53
1019  ITL   20/01/1997    NaN     71.932 i %28/06/24 15:19:56
1020  DKK   18/11/1996    NaN      90.14 i %28/06/24 15:35:22
1021  ITL   15/10/1996    NaN     91.011 i %28/06/24 15:22:53